spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: pool-back

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    validate-migration-naming: true

server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: ${app.security.session-timeout-minutes}m
      cookie:
        same-site: ${COOKIE_SAME_SITE:lax}
        secure: ${COOKIE_SECURE:false}

app:
  security:
    # Secret Key dùng để mã hóa Remember Me Token (Trên Production CẦN đổi chuỗi này thành biến môi trường)
    remember-me-key: ${REMEMBER_ME_KEY:PoolManagementDevRememberMeKey}

    # Timeout của Session đăng nhập (Dev: 60 phút)
    session-timeout-minutes: 60

    # Hạn sử dụng của Remember Me Cookie
    remember-me-cookie-max-age-days: 30

    # Cấu hình CSRF cho ReactJS
    csrf-header-name: "X-XSRF-TOKEN"
    csrf-cookie-name: "XSRF-TOKEN"

    # Danh sách các domain frontend được phép gọi API (CORS)
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

poolm:
  alert:
    expire-threshold-days: 5
    absent-threshold-days: 7
  enrollment:
    duration-days: 45
    default-total-quota: 12