spring:
  jpa:
    show-sql: false

    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.springframework.security: WARN

server:
  forward-headers-strategy: framework

app:
  security:
    # BẮT BUỘC phải set biến môi trường này trên Production (không có default)
    remember-me-key: ${REMEMBER_ME_KEY}

    # Danh sách domain frontend thực tế trên Production
    allowed-origins:
      - ${CORS_ALLOWED_ORIGIN:https://your-production-domain.com}